<?xml version="1.0"?>
<package format="3">
  <name>tidal_vehicle_autonomy</name>
  <version>0.0.1</version>
  <description>Perception, planning, avoidance and mission logic.</description>
  <maintainer email="team@example.com">One Wish Coders</maintainer>
  <license>Apache-2.0</license>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>rclpy</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>tidal_vehicle_interfaces</exec_depend>
  <test_depend>python3-pytest</test_depend>
  <export><build_type>ament_python</build_type></export>
</package>
