cmake_minimum_required(VERSION 3.16)
project(gz_sink CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(gz-transport13 REQUIRED)
find_package(gz-msgs10 REQUIRED)
add_executable(gz_sink gz_sink.cc)
target_link_libraries(gz_sink gz-transport13::gz-transport13 gz-msgs10::gz-msgs10)
add_executable(gz_grab gz_grab.cc)
target_link_libraries(gz_grab gz-transport13::gz-transport13 gz-msgs10::gz-msgs10)
